CREATE TABLE usuario (
  ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  login TINYTEXT NOT NULL,
  password TINYTEXT NOT NULL,
  nivel_acceso SMALLINT(4) UNSIGNED NOT NULL DEFAULT '100',
  nombre TINYTEXT NOT NULL,
  apellidos TINYTEXT,
  telefono VARCHAR(9),
  email TINYTEXT NOT NULL,
  direccion TINYTEXT,
  PRIMARY KEY  (ID),
  UNIQUE KEY ID (ID)
) TYPE=INNODB;

CREATE TABLE categoria (
  ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  deporte VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID (ID),
  UNIQUE KEY (deporte)
) TYPE=INNODB;

CREATE TABLE liga (
  ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  usuario MEDIUMINT UNSIGNED NOT NULL,
  nombre TINYTEXT NOT NULL,
  deporte MEDIUMINT UNSIGNED,
  metodo_puntuacion TINYTEXT NOT NULL,
  ptos_victoria MEDIUMINT(6) NOT NULL,
  ptos_empate MEDIUMINT(6) NOT NULL,
  ptos_derrota MEDIUMINT(6) NOT NULL,
  INDEX (deporte),
  FOREIGN KEY (deporte) REFERENCES categoria (ID)
    ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX (usuario),
  FOREIGN KEY (usuario) REFERENCES usuario (ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY  (ID),
  UNIQUE KEY ID (ID)
) TYPE=INNODB;

CREATE TABLE categoria_candidata (
  ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre TINYTEXT NOT NULL,
  liga MEDIUMINT UNSIGNED NOT NULL,
  INDEX (liga),
  FOREIGN KEY (liga) REFERENCES liga (ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (ID),
  UNIQUE KEY ID (ID)
) TYPE=INNODB;

CREATE TABLE equipo (
  ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre TINYTEXT NOT NULL,
  campo TINYTEXT,
  liga MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY  (ID),
  UNIQUE KEY ID (ID),
  INDEX (liga),
  FOREIGN KEY (liga) REFERENCES liga (ID)
    ON DELETE CASCADE ON UPDATE CASCADE
) TYPE=INNODB;

CREATE TABLE jornada (
  ID MEDIUMINT UNSIGNED NOT NULL, -- numero de jornada dentro de la liga
  fecha DATE,
  liga MEDIUMINT UNSIGNED NOT NULL,
  INDEX (liga),
  FOREIGN KEY (liga) REFERENCES liga (ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY  (ID, liga)
) TYPE=INNODB;

CREATE TABLE partido (
  ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT, -- numero de partido dentro de la jornada
  local MEDIUMINT UNSIGNED NOT NULL,
  visitante MEDIUMINT UNSIGNED NOT NULL,
  fecha DATE,
  hora TIME,
  campo TINYTEXT,
  detalles TEXT,
  jornada MEDIUMINT UNSIGNED NOT NULL,
  liga MEDIUMINT UNSIGNED NOT NULL,
  INDEX (jornada, liga),
  FOREIGN KEY (jornada, liga) REFERENCES jornada (ID, liga)
    ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY  (ID, jornada, liga)
) TYPE=INNODB;

CREATE TABLE juega (
  tantos_local SMALLINT UNSIGNED,
  tantos_visitante SMALLINT UNSIGNED,
  partido MEDIUMINT UNSIGNED NOT NULL,
  jornada MEDIUMINT UNSIGNED NOT NULL,
  liga MEDIUMINT UNSIGNED NOT NULL,
  INDEX (partido, jornada, liga),
  FOREIGN KEY (partido, jornada, liga) REFERENCES partido (ID, jornada, liga)
    ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY  (partido, jornada, liga)
) TYPE=INNODB;

